<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Core\**" />
    <Compile Remove="Infrastructure\**" />
    <EmbeddedResource Remove="Core\**" />
    <EmbeddedResource Remove="Infrastructure\**" />
    <None Remove="Core\**" />
    <None Remove="Infrastructure\**" />
    <Page Remove="Core\**" />
    <Page Remove="Infrastructure\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Api\Contracts\" />
    <Folder Include="Api\Controllers\" />
    <Folder Include="Api\Filters\Auth\Swagger\" />
    <Folder Include="Clients\AngularSPA\" />
    <Folder Include="Clients\WPFApp\" />
    <Folder Include="Tests\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Core\Core.csproj" />
    <ProjectReference Include="Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
