<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Api\Contracts\" />
    <Folder Include="Api\Controllers\" />
    <Folder Include="Api\Filters\Auth\Swagger\" />
    <Folder Include="Clients\AngularSPA\" />
    <Folder Include="Clients\WPFApp\" />
    <Folder Include="Core\Application\DTOs\" />
    <Folder Include="Core\Application\UseCases\GetZipCode\" />
    <Folder Include="Core\Application\UseCases\UpdateAddress\" />
    <Folder Include="Core\Domain\BusinessRules\" />
    <Folder Include="Core\Domain\Events\" />
    <Folder Include="Infrastructure\Correios\" />
    <Folder Include="Infrastructure\Http\" />
    <Folder Include="Infrastructure\Observability\Serilog\" />
    <Folder Include="Infrastructure\Persistence\" />
    <Folder Include="Infrastructure\Resilience\" />
    <Folder Include="Infrastructure\ZipCode\" />
    <Folder Include="Tests\" />
  </ItemGroup>

</Project>
